spring:
  ai:
    ollama:
      base-url: http://localhost:11434
      chat:
        model: qwen3:8b
        temperature: 0.2
        num-predict: 1000

#logging:
#  level:
#    org.springframework.ai.chat.client.advisor: DEBUG


